name: widget_quiz
description: Widget Quiz!
version: 1.0.0+2
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flare_flutter: any
  mono_kit: any
  provider: any
  simple_logger: any
  url_launcher: any
  rxdart: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/data/
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_foreground: 'assets/icon/icon_foreground.png'
  adaptive_icon_background: 'assets/icon/icon_background.png'
